name: Example
on: [push]
jobs:
 Example:
   name: Example
   strategy:
     matrix:
       os: [ubuntu-latest, macos-latest, windows-latest]
   runs-on: ${{ matrix.os }}
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Npm install
     run:  npm i
   - name: Setup CLI
     uses: jfrog/setup-jfrog-cli@v2
     env:
         JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
   - name: Audit
     run: |
         # Audit your project
         jf audit
