name: "Test"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
#     env: 
#       JFROG_CLI_BUILD_NAME: override-build-name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: yahavi/setup-jfrog-cli@dont-override-env
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - run: |
          jf npmc --repo-resolve=npm --server-id-resolve=ecosys
          jf npm i
          jf rt bp
