name: "Conditional upload example"
on:
  push:
    branches:
      - 'master'
      
jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Setup JFrog CLI
        uses: actions/checkout@v2
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - run: |
          jf npm-config --repo-resolve=default-npm-virtual --repo-deploy=default-npm-virtual

      - name: Conditional Deploy
        run: |
          # Build your project
          jf npm install
          # Deploy to configured Artifactory only if scan completed successfully
          jf npm publish --scan
